### ISSUE TITLE
Create example Pareto chart

### ISSUE THREAD

**Issue by remomueller** [sleepepi/lofthf.study#1]
https://www.highcharts.com/demo/pareto

**Comment by remomueller** [comment]
cc @mrueschman, can you provide a sample data that would be used?

**Comment by mrueschman** [comment]
Let's setup an example one for: "Reasons for participant disinterest"

![image](https://user-images.githubusercontent.com/707167/48208745-7fb8d880-e341-11e8-9451-f405c68e8fc7.png)

Let's pretend we have the following numbers of subjects indicating these reasons:

67 - Time commitment too great 
59 - Too difficult traveling to appointments 
27 - Study compensation too low 
15 - Not comfortable with randomization 
8 - Unable to complete screening PSG 
4 - Other reasons

180 total respondents

**Comment by remomueller** [comment]
Thanks!
