### ISSUE TITLE
Allow documents to be renamed

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/lofthf.study#14]
If possible, might be nice to allow. Not a major priority.

**Comment by remomueller** [comment]
So I was able to get this working locally with Carrierwave configured for local files, however we still need to see if this implementation works well in the S3 environment. This rename preserves the extension as well, so even if you try to modify `myfile.pdf` to `myfile.doc` for example, it won't work, it will rename the file to `myfile.doc.pdf`. Same with dropping off the file extension in the name as a whole, it will reappend it.
