### ISSUE TITLE
Remove "complete your profile" widget from dashboard

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/lofthf.study#20]
I want people to get to what they need on the site more quickly, and I get a sense some people just don't like to put profile photos up, so they will be engaged in an eternal struggle with the "complete your profile" prompt (since it can't be dismissed).

Also relevant to HELP-DS, which presents the user with an eternally spinning shape as the site awaits profile completion. 🤣

**Comment by remomueller** [comment]
Closed by 02e273c0cf977a4741654c8766c6e4374fc8a567.
