### ISSUE TITLE
Reordering of reports on pages does not work

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/lofthf.study#7]
Drag/drop does not work when trying to reorder reports on pages. (Note: Drag/drop does work when reordering rows on reports themselves). 

![image](https://user-images.githubusercontent.com/707167/61382173-45adb800-a87a-11e9-8d8a-5ed8bb6313b7.png)

I cannot swap the order of the reports listed here.

**Comment by mrueschman** [comment]
Note: Doesn't seem to be an issue in PATS site.

**Comment by remomueller** [comment]
This may also be an issue on HELP-DS then, most likely a missing JavaScript file to order the pages.
